### ISSUE TITLE
Frozen at inswapper-shape

### ISSUE THREAD

**Issue by TitasDas** [s0md3v/roop#22]
I seem to be stuck here while running - 

> 112, 112]  C:\Users\TD/.insightface\models\buffalo_l\w600k_r50.onnx127.5  recognition127.5
['None', 3, 112, 112]set det-size:  127.5(640, 640)
127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]

Any help or direction is appreciated.

**Comment by s0md3v** [comment]
Are you sure it's stuck and not just taking a long to work?

One way to make sure is to open whatever directory you ran in from in file explorer and look for a folder named after the video title. It should contain frames and they should be getting modified.

**Comment by TitasDas** [comment]
Yes did that already and that folder happens to be empty. Thanks for giving me a chance to clarify and provide this information as well.

**Comment by kex0** [comment]
Same issue, except the folder isn't empty in my case.

**Comment by s0md3v** [comment]
@TitasDas Are you sure ffmpeg is installed?

**Comment by LokeYourC3PH** [comment]
For Windows, I'd recommend downloading and installing [K-Lite](https://www.codecguide.com/download_kl.htm) and [FFmpeg](https://ffmpeg.org/download.html). Reboot PC after and try again.

If on Linux (or Linux Kernel on Windows), run "apt install ffmpeg". Done.

**Comment by kex0** [comment]
Alright my problem was this:
```
Traceback (most recent call last):
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "G:\roop\run.py", line 129, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "G:\roop\run.py", line 90, in start
    args['frame_paths'] = tuple(sorted(
  File "G:\roop\run.py", line 92, in <lambda>
    key=lambda x: int(x.split("/")[-1].replace(".png", ""))
ValueError: invalid literal for int() with base 10: 'pexels-fauxels-3048162-3840x2160-24fps\\0001'
```

replacing  `key=lambda x: int(x.split("/")[-1].replace(".png", ""))` at line 92
with `key=lambda x: int(''.join(filter(str.isdigit, x.split("/")[-1].replace(".png", ""))))` helped me.
and it's finally working. Now my last problem is that it's running on CPU even with `run.py --gpu`

**Comment by alessiomatt1** [comment]
> Alright my problem was this:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
>     return self.func(*args)
>   File "G:\roop\run.py", line 129, in <lambda>
>     start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
>   File "G:\roop\run.py", line 90, in start
>     args['frame_paths'] = tuple(sorted(
>   File "G:\roop\run.py", line 92, in <lambda>
>     key=lambda x: int(x.split("/")[-1].replace(".png", ""))
> ValueError: invalid literal for int() with base 10: 'pexels-fauxels-3048162-3840x2160-24fps\\0001'
> ```
> 
> replacing `key=lambda x: int(x.split("/")[-1].replace(".png", ""))` at line 92 with `key=lambda x: int(''.join(filter(str.isdigit, x.split("/")[-1].replace(".png", ""))))` helped me. and it's finally working. Now my last problem is that it's running on CPU even with `run.py --gpu`

Just for info, not working for me, on win10, thanks!

**Comment by s0md3v** [comment]
@alessiomatt1 it's because I forgot to consider windows users. The paths on linux are `/just/like/this` but on windows `C:\they\are\like\this`.

This issue will fixed in the next hour. Thanks for the heads up!

**Comment by s0md3v** [comment]
@TitasDas @alessiomatt1 This should be fixed now. Can you check please?

**Comment by alexfredo** [comment]
> Alright my problem was this:
> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
>     return self.func(*args)
>   File "G:\roop\run.py", line 129, in <lambda>
>     start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
>   File "G:\roop\run.py", line 90, in start
>     args['frame_paths'] = tuple(sorted(
>   File "G:\roop\run.py", line 92, in <lambda>
>     key=lambda x: int(x.split("/")[-1].replace(".png", ""))
> ValueError: invalid literal for int() with base 10: 'pexels-fauxels-3048162-3840x2160-24fps\\0001'
> ```
> 
> replacing `key=lambda x: int(x.split("/")[-1].replace(".png", ""))` at line 92 with `key=lambda x: int(''.join(filter(str.isdigit, x.split("/")[-1].replace(".png", ""))))` helped me. and it's finally working. Now my last problem is that it's running on CPU even with `run.py --gpu`

For me its works but sometime it's crash before replacing all the pictures, it s display this error message :
  Pattern type 'glob' was selected but globbing is not supported by this libavformat build
C:/capt/swapface//1/*.png: Function not implemented

**Comment by s0md3v** [comment]
@alexfredo I pushed a patch. Can you try again with the latest code?

**Comment by kex0** [comment]
@s0md3v I'm getting this after the windows fix commit. I'm on win11
```
Traceback (most recent call last):
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "G:\roop\run.py", line 134, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "G:\roop\run.py", line 86, in start
    Path(output_dir).mkdir(exist_ok=True)
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '\\G:\\roop\\abc'
```
The video filename is `abc.mp4`

**Comment by alexfredo** [comment]
with the latest version I have this bug :
python run.py --gpu

Traceback (most recent call last):
  File "J:\roop\run.py", line 3, in <module>
    import core.globals
ModuleNotFoundError: No module named 'core.globals'

**Comment by s0md3v** [comment]
I am sorry, I'm an idiot. Forgot to upload that file. Try now :(

**Comment by alessiomatt1** [comment]
For sure there is something else involved cause Im not really an expert, but Im stuck again to inswapper-shape, here's the output to python run.py on windows 11 

`Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
C:\Users\Alessio\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Alessio\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Alessio\Desktop\roop-main (5)\roop-main\run.py", line 141, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "C:\Users\Alessio\Desktop\roop-main (5)\roop-main\run.py", line 93, in start
    Path(output_dir).mkdir(exist_ok=True)
  File "C:\Users\Alessio\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [WinError 123] La sintassi del nome del file, della directory o del volume non è corretta: '\\C:\\Users\\Alessio\\Downloads\\document_6019231326282976957'
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
find model: C:\Users\Alessio/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
find model: C:\Users\Alessio/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
find model: C:\Users\Alessio/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
find model: C:\Users\Alessio/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
find model: C:\Users\Alessio/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
find model: C:\Users\Alessio/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]`

**Comment by alexfredo** [comment]
I m stuck at :
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]

**Comment by s0md3v** [comment]
@alessiomatt1 Your error should be fixed now.

**Comment by s0md3v** [comment]
@alessiomatt1pushed another fix, see if it works. Sorry this is taking too long, I'm not windows.

**Comment by alessiomatt1** [comment]
> @alessiomatt1pushed another fix, see if it works. Sorry this is taking too long, I'm not on windows.

Ohw, no problem, btw thanks!

I will output u my output, lol

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
DON'T WORRY. IT'S NOT STUCK.
DON'T WORRY. IT'S NOT STUCK.
DON'T WORRY. IT'S NOT STUCK.
DON'T WORRY. IT'S NOT STUCK.
DON'T WORRY. IT'S NOT STUCK.

C:\Users\Alessio\AppData\Local\Programs\Python\Python310\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
"ffprobe" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
"ffmpeg" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
"ffmpeg" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Alessio\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Alessio\Desktop\roop-main (8)\roop-main\run.py", line 144, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "C:\Users\Alessio\Desktop\roop-main (8)\roop-main\run.py", line 109, in start
    start_processing()
  File "C:\Users\Alessio\Desktop\roop-main (8)\roop-main\run.py", line 49, in start_processing
    for i in range(0, len(frame_paths), n):
ValueError: range() arg 3 must not be zero
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
find model: C:\Users\Alessio/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
find model: C:\Users\Alessio/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
find model: C:\Users\Alessio/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\Alessio/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
find model: C:\Users\Alessio/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
find model: C:\Users\Alessio/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]

**Comment by s0md3v** [comment]
@alessiomatt1 You don't have ffmpeg installed. Its mentioned in the README that it should be installed.

**Comment by alessiomatt1** [comment]
> @alessiomatt1 You don't have ffmpeg installed. Its mentioned in the README that it should be installed.

im an idiot

**Comment by LokeYourC3PH** [comment]
> > @alessiomatt1 You don't have ffmpeg installed. Its mentioned in the README that it should be installed.
> 
> im an idiot

I provided the links a while ago, should've been the first thing for you guys to try if you didn't know if you had it or not 😅

**Comment by kex0** [comment]
```
[image2 @ 000001a2031d9740] Pattern type 'glob' was selected but globbing is not supported by this libavformat build
C:\Users\dijak\Downloads\kokot\\abc\*.png: Function not implemented
ffmpeg version N-109948-ge026e29460-20230301 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (crosstool-NG 1.25.0.90_cf9beb1)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230301
  libavutil      58.  3.100 / 58.  3.100
  libavcodec     60.  5.100 / 60.  5.100
  libavformat    60.  4.100 / 60.  4.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  4.100 /  9.  4.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
C:\Users\dijak\Downloads\kokot\\abc\output.mp4: No such file or directory
Traceback (most recent call last):
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\dijak\\Downloads\\kokot\\\\abc{sep}output.mp4' -> 'C:\\Users\\dijak\\Downloads\\kokot\\output.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\roop\run.py", line 118, in <module>
    start()
  File "G:\roop\run.py", line 111, in start
    add_audio(output_dir, target_path, args['keep_frames'], args['output_file'])
  File "G:\roop\core\utils.py", line 41, in add_audio
    shutil.move(output_dir + "{sep}output.mp4", save_to)
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dijak\\Downloads\\kokot\\\\abc{sep}output.mp4'
```
+ it's still using CPU even with `--gpu`

Thank you very much for your efforts

**Comment by LokeYourC3PH** [comment]
> ```
>     * it's still using CPU even with `--gpu`
> 
> Thank you very much for your efforts

I was having that feeling as well actually. I use Linux Kernel Ubuntu 22.04 on Windows 11 Pro like I said, but it was slow as fuck for a 17MB (took like almost an hour), so GPU I feel like isn't actually utilized even when installed and defined.

**Comment by s0md3v** [comment]
I'm losing my mind with these paths lmao. WAIT, let me try again.

**Comment by s0md3v** [comment]
Are you sure about the GPU thing @kex0 ? It works fine on my machine.
```
Applied providers: ['ROCMExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'ROCMExecutionProvider': {'tunable_op_tuning_enable': '0', 'tunable_op_enable': '0', 'miopen_conv_exhaustive_search': '0', 'do_copy_in_default_stream': '1', 'arena_extend_strategy': 'kNextPowerOfTwo', 'gpu_external_empty_cache': '0', 'gpu_external_free': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'miopen_conv_use_max_workspace': '1', 'device_id': '0'}}
```

**Comment by s0md3v** [comment]
That path thing should be fixed now.

**Comment by LokeYourC3PH** [comment]
> Are you sure about the GPU thing @kex0 ? It works fine on my machine.
> 
> ```
> Applied providers: ['ROCMExecutionProvider', 'CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}, 'ROCMExecutionProvider': {'tunable_op_tuning_enable': '0', 'tunable_op_enable': '0', 'miopen_conv_exhaustive_search': '0', 'do_copy_in_default_stream': '1', 'arena_extend_strategy': 'kNextPowerOfTwo', 'gpu_external_empty_cache': '0', 'gpu_external_free': '0', 'gpu_external_alloc': '0', 'gpu_mem_limit': '18446744073709551615', 'miopen_conv_use_max_workspace': '1', 'device_id': '0'}}
> ```

I do not have what you have, hold on.

Here: 
![Screenshot 2023-05-29 233131](https://github.com/s0md3v/roop/assets/5807595/50c1475f-7c6b-4990-84f2-5dc46c711b48)

**Comment by s0md3v** [comment]
Do you have the latest code? What's the output of following python code:

```
import onnxruntime
onnxruntime.get_available_providers()
```

**Comment by kex0** [comment]
I'm still getting this path error. I'm probably using the command wrong am I not?
```
Traceback (most recent call last):
  File "G:\roop\run.py", line 118, in <module>
    start()
  File "G:\roop\run.py", line 111, in start
    add_audio(output_dir, target_path, args['keep_frames'], args['output_file'])
  File "G:\roop\core\utils.py", line 41, in add_audio
    shutil.move(output_dir + f"{sep}output.mp4", save_to)
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dijak\\Downloads\\kokot\\\\abc\\output.mp4'
```

My command `python run.py --gpu -f "C:\Users\dijak\Downloads\kokot\images\image(14).jpg" -t "C:\Users\dijak\Downloads\kokot\abc.mp4" -o "C:\Users\dijak\Downloads\kokot\"`

My CPU and GPU usage during the process:
![image](https://github.com/s0md3v/roop/assets/46696708/c41d6fcf-3598-45b6-96c9-e06020f421af)
![image](https://github.com/s0md3v/roop/assets/46696708/973f192f-f4ea-4453-a274-61bd2b4c8594)

get_available_providers()
```
>>> import onnxruntime
>>> print(onnxruntime.get_available_providers())
['CPUExecutionProvider']
>>>
```

pip list
![WindowsTerminal_7wwb8DFcqX](https://github.com/s0md3v/roop/assets/46696708/18534d86-6c1e-4fb3-8b7c-c706265cb1d1)

**Comment by s0md3v** [comment]
@kex0 You don't have `cuda` installed.

**Comment by kex0** [comment]
@s0md3v I do 
nvcc -version
```
G:\roop>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
```

**Comment by s0md3v** [comment]
@kex0 well, if it was set-up correctly, `CUDAExecutionProvider` would be present in your output

**Comment by FurkanGozukara** [comment]
same issue

i have installed in a venv

not using cuda gpu


![image](https://github.com/s0md3v/roop/assets/19240467/14090638-11a1-44e1-af19-d381d289fd33)


![image](https://github.com/s0md3v/roop/assets/19240467/1d74cb85-a98a-467c-8238-3cabd002e88c)


i am working on a tutorial video

![image](https://github.com/s0md3v/roop/assets/19240467/fc4f16d1-284b-4032-9b2c-33babfe5f94b)

**Comment by kex0** [comment]
> @kex0 well, if it was set-up correctly, `CUDAExecutionProvider` would be present in your output

and it was before `onnxruntime` was added to `requirements.txt` I think
https://github.com/s0md3v/roop/issues/2#issuecomment-1566973915

**Comment by s0md3v** [comment]
For your paths error @kex0, I have pushed another fixed. See if that works.

**Comment by FurkanGozukara** [comment]
testing with newest git pull

> same issue
> 
> i have installed in a venv
> 
> not using cuda gpu
> 
> ![image](https://user-images.githubusercontent.com/19240467/241755673-14090638-11a1-44e1-af19-d381d289fd33.png)
> 
> ![image](https://user-images.githubusercontent.com/19240467/241755718-1d74cb85-a98a-467c-8238-3cabd002e88c.png)
> 
> i am working on a tutorial video
> 
> ![image](https://user-images.githubusercontent.com/19240467/241755835-fc4f16d1-284b-4032-9b2c-33babfe5f94b.png)

testing with newest git pull

**Comment by FurkanGozukara** [comment]
still stuck with newest git pull

not using cuda

![image](https://github.com/s0md3v/roop/assets/19240467/6356d13d-60d1-4403-8bfc-38186b7c6ef6)

**Comment by TitasDas** [comment]
Ok so I am still stuck on the same error that I had posted except now it goes onto nine lines as opposed to four lines as before. 

> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape:inswapper-shape:  [1, 3, 128, 128]
[1, 3, 128, 128]inswapper-shape:
inswapper-shape:  [1, 3, 128, 128]
[1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]

However there is another thing I noticed - somewhere in the beginning I get this error :

>  FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
[**mov,mp4,m4a,3gp,3g2,mj2 @ 0000020a32badbc0] moov atom not found
C:/Users/TD/Desktop/abc_1.mp4: Invalid data found when processing input**
C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3)

Which tells me that the input video file itself is not being read properly. 
I am wondering should I fix this numpy version? Is it expected to work just fine without it?
Also, I do have ffmpeg and k-lite installed. 

@s0md3v Happy to offer any assistance to solve this as well, do you have any idea as to what else we could check to resolve this?

**Comment by s0md3v** [comment]
@TitasDas Googling "moov atom not found" says your video is corrupt. Try with another video ig.

**Comment by LokeYourC3PH** [comment]
> @kex0 You don't have `cuda` installed.

I'm installing cuda now in that environment and will see if it works, I'll try your output commands too.

**Comment by kex0** [comment]
```
Traceback (most recent call last):
  File "G:\roop\run.py", line 118, in <module>
    start()
  File "G:\roop\run.py", line 111, in start
    add_audio(output_dir, target_path, args['keep_frames'], args['output_file'])
  File "G:\roop\core\utils.py", line 41, in add_audio
    shutil.move(output_dir + f"{sep}output.mp4", save_to)
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dijak\\Downloads\\kokot\\\\abc\\output.mp4'
```

and there's a typo  on line 95
output_dir = output_dir.lstrip("\\").rstri("\\")
correct
output_dir = output_dir.lstrip("\\").rstrip("\\")

**Comment by FurkanGozukara** [comment]
> @TitasDas Googling "moov atom not found" says your video is corrupt. Try with another video ig.

here my full logs

[Uploading full logs.txt…]()

**Comment by s0md3v** [comment]
my bad @kex0, fixed :(

**Comment by FurkanGozukara** [comment]
my full logs attached
[full logs.txt](https://github.com/s0md3v/roop/files/11592633/full.logs.txt)
 @s0md3v 

i want to make a tutorial for this

by the way it is using 30 gb RAM 🗡️ 

```
Microsoft Windows [Version 10.0.19045.2965]
(c) Microsoft Corporation. All rights reserved.

F:\roop\venv\Scripts>activate

(venv) F:\roop\venv\Scripts>cd..

(venv) F:\roop\venv>cd..

(venv) F:\roop>python run.py
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\King/.insightface\models\buffalo_l\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\King/.insightface\models\buffalo_l\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\King/.insightface\models\buffalo_l\det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\King/.insightface\models\buffalo_l\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: C:\Users\King/.insightface\models\buffalo_l\w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
DON'T WORRY. IT'S NOT STUCK.
DON'T WORRY. IT'S NOT STUCK.
DON'T WORRY. IT'S NOT STUCK.
DON'T WORRY. IT'S NOT STUCK.
DON'T WORRY. IT'S NOT STUCK.

F:\roop\venv\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python3108\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "F:\roop\run.py", line 144, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "F:\roop\run.py", line 95, in start
    output_dir = output_dir.lstrip("\\").rstri("\\")
AttributeError: 'str' object has no attribute 'rstri'
```

**Comment by LokeYourC3PH** [comment]
Alright, installed cuda-dev, getting this with Python output:
![Screenshot 2023-05-29 235950](https://github.com/s0md3v/roop/assets/5807595/9d7a6f29-5ab6-4297-bc9b-549dd749e0be)

**Comment by s0md3v** [comment]
@LokeYourC3PH and you said it worked before? did you install `onnxruntime` and then it stopped working?

**Comment by FurkanGozukara** [comment]
> @LokeYourC3PH and you said it worked before? did you install `onnxruntime` and then it stopped working?

does it require certain size image and video input? certain format etc? i did a fresh correct installation with a fresh venv

with python 3.10.9 on windows

**Comment by LokeYourC3PH** [comment]
> @LokeYourC3PH and you said it worked before? did you install `onnxruntime` and then it stopped working?

Nono it never did since the beginning, only CPU ever worked. I didn't have CUDA, so now I have but it still does not work.

**Comment by s0md3v** [comment]
@LokeYourC3PH let me know if you get it working. I will create a wiki page about common installation problems.

@FurkanGozukara No, it works with all mainstream formats. If you have everything installed as mentioned in README, try again with the latest changes, I fixed a few things.

**Comment by FurkanGozukara** [comment]
> @LokeYourC3PH let me know if you get it working. I will create a wiki page about common installation problems.
> 
> @FurkanGozukara No, it works with all mainstream formats. If you have everything installed as mentioned in README, try again with the latest changes, I fixed a few things.

i doubt that

trying with another video and progressed much more

![image](https://github.com/s0md3v/roop/assets/19240467/e6a98697-e296-44ed-ab5e-1eda45059fdb)


looks like gonna work

**Comment by LokeYourC3PH** [comment]
> @LokeYourC3PH let me know if you get it working. I will create a wiki page about common installation problems.
> 
> @FurkanGozukara No, it works with all mainstream formats. If you have everything installed as mentioned in README, try again with the latest changes, I fixed a few things.

I think the issue is WSL 2. I gotta enable NVIDIA CUDA support in WSL 2 first I think for it to work. I'll get back to you when I got it working.

**Comment by FurkanGozukara** [comment]
> @LokeYourC3PH let me know if you get it working. I will create a wiki page about common installation problems.
> 
> @FurkanGozukara No, it works with all mainstream formats. If you have everything installed as mentioned in README, try again with the latest changes, I fixed a few things.

wit different video it worked but got path error

`F:/roop/test1\output.mp4: No such file or directory
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python3108\lib\shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'F:/roop/test1\\output.mp4' -> 'F:/roop/output.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python3108\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "F:\roop\run.py", line 144, in <lambda>
    start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
  File "F:\roop\run.py", line 111, in start
    add_audio(output_dir, target_path, args['keep_frames'], args['output_file'])
  File "F:\roop\core\utils.py", line 41, in add_audio
    shutil.move(output_dir + f"{sep}output.mp4", save_to)
  File "C:\Python3108\lib\shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "C:\Python3108\lib\shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Python3108\lib\shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'F:/roop/test1\\output.mp4'`

**Comment by kex0** [comment]
I'm not using WSL and as I mentioned before, it did indeed find `CUDAExecutionProvider` before
https://github.com/s0md3v/roop/issues/2#issuecomment-1566973915

**Comment by FurkanGozukara** [comment]
but i see frames are changed haha

![image](https://github.com/s0md3v/roop/assets/19240467/fb9fc716-a59c-4193-ae63-65da8478b7c1)

**Comment by FurkanGozukara** [comment]
what is the image quality it can get?

it changed the face but quality very bad 🗡️ 



![image](https://github.com/s0md3v/roop/assets/19240467/6425eec7-2778-407d-8c09-8659d46ab2e8)

**Comment by LokeYourC3PH** [comment]
> what is the image quality it can get?
> 
> it changed the face but quality very bad 🗡️
> 
> ![image](https://user-images.githubusercontent.com/19240467/241762772-6425eec7-2778-407d-8c09-8659d46ab2e8.png)

Yep, that's the training model it uses. 128x128 is the highest. That 500MB file you download, that's the model. Higher unfortunately isn't available, but I hope some day.

**Comment by FurkanGozukara** [comment]
> > what is the image quality it can get?
> > it changed the face but quality very bad 🗡️
> > ![image](https://user-images.githubusercontent.com/19240467/241762772-6425eec7-2778-407d-8c09-8659d46ab2e8.png)
> 
> Yep, that's the training model it uses. 128x128 is the highest. That 500MB file you download, that's the model. Higher unfortunately isn't available, but I hope some day.

by the way frames changed but it failed to generate output video file

**Comment by Maki9009** [comment]
> > what is the image quality it can get?
> > it changed the face but quality very bad 🗡️
> > ![image](https://user-images.githubusercontent.com/19240467/241762772-6425eec7-2778-407d-8c09-8659d46ab2e8.png)
> 
> Yep, that's the training model it uses. 128x128 is the highest. That 500MB file you download, that's the model. Higher unfortunately isn't available, but I hope some day.

how about once all the swap frames went throught, it starts using CodeFormer https://github.com/sczhou/CodeFormer to enhance the quality?

**Comment by kex0** [comment]
Alright, the way to fix the GPU usage problem is you have to uninstall both `onnxruntime` and `onnxruntime-gpu` and then only install `onnxruntime-gpu`
Now I see `CUDAExecutionProvider `

These pesky paths are still issue though:
```
Traceback (most recent call last):
  File "G:\roop\run.py", line 118, in <module>
    start()
  File "G:\roop\run.py", line 96, in start
    Path(output_dir).mkdir(exist_ok=True)
  File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '\\C:\\Users\\dijak\\Downloads\\kokot\\abc'
```

**Comment by TitasDas** [comment]
I am getting the frames in the output and it has almost worked. However this is where it gets an error again. 
> [image2 @ 00000200f8f16340] Pattern type 'glob' was selected but globbing is not supported by this libavformat build
[in#0 @ 00000200f8f161c0] Error opening input: Function not implemented
[in#0 @ 000002bbc9f47680] Error opening input: No such file or directory

And then this file path error - 

> FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:/Users/TD/Desktop/abc{sep}output.mp4' -> 'L:/Path/To/My/output.mp4'

During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
>   File "C:\ProgramData\Anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
>     return self.func(*args)
>   File "run.py", line 144, in <lambda>
>     start_button = tk.Button(window, text="Start", bg="green", command=lambda: [save_file(), start()])
>   File "run.py", line 111, in start
>     add_audio(output_dir, target_path, args['keep_frames'], args['output_file'])
>   File "C:\Users\TD\Desktop\Work\roop\core\utils.py", line 41, in add_audio
>     shutil.move(output_dir + "{sep}output.mp4", save_to)
>   File "C:\ProgramData\Anaconda3\lib\shutil.py", line 805, in move
>     copy_function(src, real_dst)
>   File "C:\ProgramData\Anaconda3\lib\shutil.py", line 435, in copy2
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "C:\ProgramData\Anaconda3\lib\shutil.py", line 264, in copyfile
>     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
> FileNotFoundError: [Errno 2] No such file or directory: 'L:/Path/To/MyOutput/abc{sep}output.mp4'

However I do confirm that the previous error was due to a corrupt video file that fixed most of it, now I can see the frames with the transformed face.

**Comment by TitasDas** [comment]
> how about once all the swap frames went throught, it starts using CodeFormer https://github.com/sczhou/CodeFormer to enhance the quality?

Looking into this

**Comment by adam-andrzejczak** [comment]
I'm also stuck at inswapper-shape:  [1, 3, 128, 128], however it did generate output frames and movie. However x2, it is the same as input movie, no face swap. Process takes up 27 GB and does not end, with many subprocesses spawned that consume 0% of CPU power. Could you provide us with a sample video and picture for which you know the code is working? I tested it on CPU.

**Comment by LokeYourC3PH** [comment]
> Alright, the way to fix the GPU usage problem is you have to uninstall both `onnxruntime` and `onnxruntime-gpu` and then only install `onnxruntime-gpu` Now I see `CUDAExecutionProvider `
> 
> These pesky paths are still issue though:
> 
> ```
> Traceback (most recent call last):
>   File "G:\roop\run.py", line 118, in <module>
>     start()
>   File "G:\roop\run.py", line 96, in start
>     Path(output_dir).mkdir(exist_ok=True)
>   File "C:\Users\dijak\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1175, in mkdir
>     self._accessor.mkdir(self, mode)
> OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '\\C:\\Users\\dijak\\Downloads\\kokot\\abc'
> ```

Can confirm that running "pip uninstall onnxruntime" and "pip uninstall onnxruntime-gpu" and then "pip install onnxruntime-gpu" even works on WSL 2. Thanks :)

**Comment by adam-andrzejczak** [comment]
Is your input file an mp4 clip? I had the same issue and it was solved by converting source to mp4 wia ffmpeg.
It didn't swap face though as I described in the comment above.

**Comment by Maki9009** [comment]
Now it seems to have stopped working, after the new git pull, it cuts the video up, but just wont continue to swapping

**Comment by LokeYourC3PH** [comment]
Uhh so, I get different output for available providers now (GPU still doesn't work, but it is recognized as such:):
![Screenshot 2023-05-30 021546](https://github.com/s0md3v/roop/assets/5807595/fb551d42-fe1f-4c1b-8150-d8b45f83a6aa)

**Comment by s0md3v** [comment]
I have tested the program on both linux and windows. With the latest patch, its working **if everything is installed well**.

I'm closing this issue for now. Thanks for being patient!

**Comment by MatroskeN** [comment]
For those, who still struggling with freeze at inswapper-shape:
It turned out, for me it was caused by cyrillic symbols in the path to image, video or output. I don't really know which one, it was all three actually, i'm an idiot.
So i've created test folder with correct path and it started working. Hope it'll help someone

**Comment by trytofly94** [comment]
I'm on mac and also get stuck at converting a gif or video.
The folder gets created and original frames exported but the don't change, it just stops there.
This is the end of the output:

> Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]
inswapper-shape: [1, 3, 128, 128]

And this is a warning from the same operation a bit further upwards:
> Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/lennart/Stable Diffusion/roop/run.py", line 230, in <lambda>
    start_button = tk.Button(window, text="Start", bg="#f1c40f", relief="flat", borderwidth=0, highlightthickness=0, command=lambda: [save_file(), start()])
                                                                                                                                                   ^^^^^^^
  File "/Users/lennart/Stable Diffusion/roop/run.py", line 183, in start
    start_processing()
  File "/Users/lennart/Stable Diffusion/roop/run.py", line 68, in start_processing
    for i in range(0, len(frame_paths), n):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: range() arg 3 must not be zero

I don't really know how to solve this...

**Comment by gosver** [comment]
Frozen on this step
i tried reinstall, reboot, but nothing help me


D:\Desktop\projects\roop\venv\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4

**Comment by LokeYourC3PH** [comment]
> Frozen on this step i tried reinstall, reboot, but nothing help me
> 
> D:\Desktop\projects\roop\venv\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times `max(M, N)` where M and N are the input matrix dimensions. To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`. P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4

You hit the NSFW filter.
